###############
#####  1  #####
###############

# generate 100 i.i.d Bernoulli RVs with p=0.3
n = 100
p = 0.3
y = rbinom(n,1,p)

# generate 1000 samples of the sum of Bernoulli(0.3) RVs
y = rep(NA,1000)
for (i in 1:1000){
  y[i]=sum(rbinom(n,1,p))
} 

# PDF of the sum
hist(y, breaks=range(y)[2]-range(y)[1],xlim=c(0,n),main='PDF of the sum')

# PDF of the theoretical distribution of the sum
plot(1:n,dbinom(1:n,n,p),xlab='n',ylab='Probability', main = 'PDF of Binomial (100,0.3)')

# PDF of approximate Gaussian RV
x=seq(1,n,0.01)
plot(x,dnorm(x,n*p,sqrt(n*p*(1-p))),xlab='n',ylab='Probability', main = 'PDF of Normal (30,21)')

# generate sums of Bernoulli(0.3) RVs for n=500, 1000 and 10000
n = c(500,1000,10000)
y1 = rep(NA,1000)
for (i in 1:1000){y1[i]=sum(rbinom(n[1],1,p))}
y2 = rep(NA,1000)
for (i in 1:1000){y2[i]=sum(rbinom(n[2],1,p))}
y3 = rep(NA,1000)
for (i in 1:1000){y3[i]=sum(rbinom(n[2],1,p))}

# PDF of the sums
par(mfrow=c(1,3))
hist(y1, nclass=20,main='PDF of the sum for n = 500')
hist(y2, nclass=20,main='PDF of the sum for n = 1000')
hist(y3, nclass=20,main='PDF of the sum for n = 10000')

# PDF of the theoretical distributions of the sums
plot(1:n[1],dbinom(1:n[1],n[1],p),xlim=c(100,200),xlab='n',ylab='Probability', 
     main = 'PDF of Binomial (500,0.3)')
plot(1:n[2],dbinom(1:n[2],n[2],p),xlim=c(200,400),xlab='n',ylab='Probability', 
     main = 'PDF of Binomial (1000,0.3)')
plot(1:n[3],dbinom(1:n[3],n[3],p),xlim=c(2800,3200),xlab='n',ylab='Probability', 
     main = 'PDF of Binomial (10000,0.3)')

# PDF of the Gaussian approximation
x1=seq(1,n[1],0.1)
plot(x1,dnorm(x1,n[1]*p,sqrt(n[1]*p*(1-p))),xlim=c(100,200),
     xlab='n',ylab='Probability', main = 'PDF of Normal (150,105)')
x2=seq(1,n[2],0.1)
plot(x2,dnorm(x2,n[2]*p,sqrt(n[2]*p*(1-p))),xlim=c(200,400),
     xlab='n',ylab='Probability', main = 'PDF of Normal (300,210)')
x3=seq(1,n[3],0.1)
plot(x3,dnorm(x3,n[3]*p,sqrt(n[3]*p*(1-p))),xlim=c(2800,3200),
     xlab='n',ylab='Probability', main = 'PDF of Normal (3000,210)')



###############
#####  2  #####
###############
par(mfrow=c(1,1))
# Generate n=100 i.i.d Poisson RVs with parameter lambda = 0:3
n = 100
lambda = 0.3
y = rpois(n,lambda)

# Generate 1000 samples of the sum of these n RVs
y = rep(NA,1000)
for (i in 1:1000){
  y[i]=sum(rpois(n,lambda))
} 

# PDF of the sum
hist(y, breaks=range(y)[2]-range(y)[1],xlim=c(0,n),main='PDF of the sum')

# PDF of the theoretical distribution of the sums
plot(1:n,dpois(1:n,n*p),xlab='n',ylab='Probability', main = 'PDF of Poisson (30)')

# PDF of approximate Gaussian RV
x=seq(1,n,0.01)
plot(x,dnorm(x,n*lambda,sqrt(n*lambda)),xlab='n',ylab='Probability', 
     main = 'PDF of Normal (30,30)')

# generate sums of Poisson(0.3) RVs for n=500, 1000 and 10000
n = c(500,1000,10000)
y1 = rep(NA,1000)
for (i in 1:1000){y1[i]=sum(rpois(n[1],lambda))}
y2 = rep(NA,1000)
for (i in 1:1000){y2[i]=sum(rpois(n[2],lambda))}
y3 = rep(NA,1000)
for (i in 1:1000){y3[i]=sum(rpois(n[3],lambda))}

# PDF of the sums
par(mfrow=c(1,3))
hist(y1, nclass=20,main='PDF of the sum for n = 500')
hist(y2, nclass=20,main='PDF of the sum for n = 1000')
hist(y3, nclass=20,main='PDF of the sum for n = 10000')

# PDF of the theoretical distributions of the sums
plot(1:n[1],dpois(1:n[1],n[1]*lambda),xlim=c(100,200),xlab='n',ylab='Probability', 
     main = 'PDF of Poisson (150)')
plot(1:n[2],dpois(1:n[2],n[2]*lambda),xlim=c(200,400),xlab='n',ylab='Probability', 
     main = 'PDF of Poisson (300)')
plot(1:n[3],dpois(1:n[3],n[3]*lambda),xlim=c(2800,3200),xlab='n',ylab='Probability', 
     main = 'PDF of Poisson (3000)')

# PDF of the Gaussian approximation
x1=seq(1,n[1],0.1)
plot(x1,dnorm(x1,n[1]*p,sqrt(n[1]*p)),xlim=c(100,200),
     xlab='n',ylab='Probability', main = 'PDF of Normal (150,150)')
x2=seq(1,n[2],0.1)
plot(x2,dnorm(x2,n[2]*p,sqrt(n[2]*p)),xlim=c(200,400),
     xlab='n',ylab='Probability', main = 'PDF of Normal (300,300)')
x3=seq(1,n[3],0.1)
plot(x3,dnorm(x3,n[3]*p,sqrt(n[3]*p)),xlim=c(2800,3200),
     xlab='n',ylab='Probability', main = 'PDF of Normal (3000,3000)')



###############
#####  3  #####
###############
n=10000
for (i in 1:1000){
  X[i]<-mean(runif(n,0,1))
}
Y = (X-0.5)/sqrt(1/12/n) 
Z = sqrt(3)*Y+2 
# ecdf(Z) is the CDF of a Gaussian RV with mean 2 and variance 3

par(mfrow=c(2,2))
hist(Z, main = 'PDF of Z')
plot(ecdf(Z), main = 'CDF of Z')

# compared with N(2,3) distribution generated by R
N = rnorm(1000,2,sqrt(3)) 
hist(N, main = 'PDF of Normal(2,3)')
plot(ecdf(N), main = 'CDF of Normal(2,3)')



###############
#####  4  #####
###############
n = seq(100,50000,100)
m = length(n)
mean1 = rep(NA,m)
mean2 = rep(NA,m)
diff1 = rep(NA,m)
diff2 = rep(NA,m)
for (i in 1:m){
  mean1[i]=mean(rbinom(n[i],6,0.3)) # sample mean
  diff1[i] = mean1[i]-6*0.3
}
for (i in 1:m){
  mean2[i]=mean(rbinom(n[i],1,0.4)) # sample mean
  diff2[i] = mean2[i]-0.4
}

plot(mean1~n, ylab = 'sample mean', main = 'Binomial(6,0.3) RVs')
abline(h=1.8,col='red')
plot(diff1~n, ylab = 'Difference', main = 'Binomial (6,0.3) RVs')
abline(h=0,col='red')
plot(mean2~n, ylab = 'sample mean', main = 'Bernoulli(0.4) RVs')
abline(h=0.4,col='red')
plot(diff2~n,ylab = 'Difference', main = 'Bernoulli(0.4) RVs')
abline(h=0,col='red')


###############
#####  5  #####
###############
n = seq(100,50000,100)
m = length(n)
SampleMean = rep(NA,m)
for (i in 1:m){
  X = rnorm(n[i],0,1)
  X2 = X^2
  SampleMean[i]=mean(X2)
}

par(mfrow=c(1,2))
hist(SampleMean)
plot(SampleMean~n)
abline(h=1, col='red')
